### ISSUE TITLE
"Extracting Downloaded File..." won't finish

### ISSUE THREAD

**Issue by bijakriyandi** [stankovski/quran-phone#112]
I just installed this app a few hours ago on my phone and PC and I found this bug on both.

**Comment by stankovski** [comment]
Jak for reporting. Will take a look iA.

**Comment by bijakriyandi** [comment]
UPDATE:
I reinstalled the app and didn't enter any other screen during download and extraction phase on both my phone and PC. After more than 15 minutes of waiting, the "Extracting Downloaded File..." seems to be stuck with five running dots keep on going and going.

It seems like the app can't start the extraction process for some reason.

**Comment by stankovski** [comment]
@bijakriyandi just to confirm, are you seeing "Loading Quran" message before that and if so how long does it take on average to reach 100%?

**Comment by stankovski** [comment]
Never mind - I found a bug! JAK for helping with the steps.

**Comment by stankovski** [comment]
Will be available in the next release
