### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by Yaser7** [stankovski/quran-phone#128]
AsSalam-u-Alaikum,

I have a recommendation to use Mus-haf Tajweed where the Ayah letters are color-coded for Maddah, Edgham and other tajweed rules. This will make reading even easier. I also would like to thank you for the great effort you put in developing this application. 
![capture](https://cloud.githubusercontent.com/assets/18307054/14315986/23d679ea-fc09-11e5-8968-f8fe7fdab551.PNG)

**Comment by stankovski** [comment]
ASA. JAK for the feedback. Currently I'm tied to the images used by Quran Android project. Please feel free to submit an issue to them here - https://github.com/quran/quran_android
