### ISSUE TITLE
Enable font resize for arabic text

### ISSUE THREAD

**Issue by kmoataz** [stankovski/quran-phone#130]
Salam Alaikom
This AWESOME app works alllllmost perfectly on tablets (e.g. Surface pro 3 with Windows 10) that it's really worth fixing those small bugs :

1. In landscape mode, font is RIDICULOUSLY gigantic. Need "Tablet Mode" (similar to Quran Android) where the app automatically displays two adjacent pages once in landscape. 

---------
Note: I repeat: this is AWESOME work! Jazakum Allah Khairan yo guys! 

KEEP it UP!

**Comment by stankovski** [comment]
Splitting into 2 issues

**Comment by stankovski** [comment]
https://github.com/stankovski/quran-phone/issues/134
