### ISSUE TITLE
Bug with Translation Mode 

### ISSUE THREAD

**Issue by IbnFaruque** [stankovski/quran-phone#135]
بِسْمِ اللهِ الرَّحْمٰنِ الرَّحِيْمِ

Assalamualaikum

May Allah reward you for your efforts. This bug is quite obvious. It occurs in the translation mode. Sometimes in the place the page should finish it repeats from the top in the same page. This is clear to the reader so its not too much of a big deal but it will be great to have this bug fixed. 

Just as I was typing this, I checked back again and this problem disappeared. So this bug comes in and goes away for different pages.

**Comment by stankovski** [comment]
JAK. I just fixed the bug (I think) Insha'Allah. It should be included in the next release.
