### ISSUE TITLE
application does not expanded for full screen in lumia 535

### ISSUE THREAD

**Issue by hubaishan** [stankovski/quran-phone#98]
When collapse on screen menu buttons in lumia 535 the application does not expanded to full screen

**Comment by stankovski** [comment]
@hubaishan can you please provide more details?

**Comment by hubaishan** [comment]
![wp_ss_20160108_0001](https://cloud.githubusercontent.com/assets/2285457/12202849/f71e3940-b63c-11e5-8c66-f6f0a325cc87.png)
![wp_ss_20160108_0002](https://cloud.githubusercontent.com/assets/2285457/12202850/f738dc0a-b63c-11e5-906f-6c750a3d5215.png)

**Comment by stankovski** [comment]
OK, got you.

**Comment by stankovski** [comment]
After some research it appears that the issue is related to the fact that the project is built using Windows Phone 8 SDK and not 8.1. I've tried upgrading to 8.1 but it broke the background audio playback.
